SELECT TOP (1000) [load]
      ,[Version]
      ,[AÑO]
      ,[MES]
      ,[TYPE]
      ,[Company Code]
      ,[Posting date]
      ,[Reference document]
      ,[Profit Center]
      ,[PC_Description]
      ,[Country]
      ,[Plant]
      ,[New Plant Name]
      ,[Customer]
      ,[Name]
      ,[City]
      ,[Campo3]
      ,[Country_Customer]
      ,[Zone (NC, Mpumalanga, etc)]
      ,[Mineral]
      ,[Type of Business]
      ,[Sold-to party]
      ,[Sold-Text]
      ,[Ship-to party]
      ,[Ship-Text]
      ,[Bill-to party]
      ,[Bill-Text]
      ,[Group]
      ,[Product]
      ,[Material_Description]
      ,[Matl_Group]
      ,[Mat_group_description]
      ,[Mat_group_ description2]
      ,[Material_type]
      ,[Material_group_description]
      ,[OUn]
      ,[Unit]
      ,[Unit2]
      ,[KG_BOX_BAG]
      ,[Kg_unit]
      ,[Unit_Box]
      ,[Unit_Rol]
      ,[Gross]
      ,[Net]
      ,[Sales Order]
      ,[PA Unit - Sales Tons]
      ,[Sales quantity]
      ,[Qty Unit2]
      ,[Unit Sales quantity]
      ,[Con/Neg/Man Price]
      ,[Base Price]
      ,[Sundry & Services]
      ,[Price/Unit]
      ,[Revenue]
      ,[Cost/Unit]
      ,[Transportation Recov]
      ,[Negotiated Price]
      ,[Stock Value]
      ,[Freight]
      ,[Intern Road Frght]
      ,[Road Freight]
      ,[Storage and Handling]
      ,[Storage/Warehouse]
      ,[Type of Business_2]
      ,[Controller]
      ,[MS_Customer_Name]
      ,[Sales manager per customer]
      ,[Profit Center2]
      ,[PC_Description2]
      ,[R1]
      ,[R2]
      ,[R2A]
      ,[R3]
      ,[R3A]
      ,[R4]
      ,[R4A]
  FROM [FIN].[26_KE24_FINAL]