use ENAEX_FIN_PRD;

create Table [FIN].[51_DOTACTION_FINAL] (
    Version VARCHAR(50) NULL,
    [G/L Fiscal Year] INT null,
    [Posting period] INT null,
    Type VARCHAR(50) NULL,
    LOAD INT null,
    [Profit Center] VARCHAR(50) NULL,
    [PC Description] VARCHAR(50) NULL,
    Country VARCHAR(50) NULL,
    [Company Code] VARCHAR(50) NULL,
    [Cost Center] VARCHAR(50) NULL,
    [CC Description] VARCHAR(50) NULL,
    [Responsible 1] VARCHAR(50) NULL,
    [Responsible 2] VARCHAR(50) NULL,
    [Responsible 3] VARCHAR(50) NULL,
    [Responsible 4] VARCHAR(50) NULL,
    [Functional area] VARCHAR(50) NULL,
    Description VARCHAR(50) NULL,
    [Group] VARCHAR(50) NULL,
    [Employee Nr] INT null,
    [Last Name] VARCHAR(50) NULL,
    Name VARCHAR(50) NULL,
    [Employee Name] VARCHAR(50) NULL,
    Gender VARCHAR(50) NULL,
    Position VARCHAR(50) NULL,
    Position_TEXT VARCHAR(50) NULL,
    [Role Category] VARCHAR(50) NULL,
    [Role Category Code] VARCHAR(50) NULL,
    Status VARCHAR(50) NULL,
    Dotacion INT NULL,
    Valor INT NULL,
    TEXT1 VARCHAR(50) NULL,
    USUARIO VARCHAR(50) NULL,
    [Employee subgroup] VARCHAR(50) NULL,
    [ID number] VARCHAR(50) NULL,
    Nationality VARCHAR(50) NULL,
    [Personnel area] VARCHAR(50) NULL,
    [PA Text] VARCHAR(50) NULL,
    birdate DATETIME NULL,
    [Joined Group] DATETIME NULL,
    Separation DATETIME NULL,
    [Employment status] VARCHAR(50) NULL 
    );