[FIN].[PWBI_20_Report_Budget_Consolidated]
[FIN].PWBI_10_EERR
[FIN].PWBI_11_RRHH
[FIN].PWBI_12_VENTAS
[FIN].PWBI_12_VENTAS_Adjusted_Cost_Sales
[FIN].PWBI_12_VENTAS_Gross_Margin
[FIN].PWBI_13_VENTAS_ConNegManPrice
[FIN].PWBI_14_VENTAS_Revenue
[FIN].PWBI_14_VENTAS_Transportation_Recov
[FIN].PWBI_15_VENTAS_Stock_Value
[FIN].PWBI_16_VENTAS_Sundry_Services
[FIN].PWBI_17_VENTAS_Freight
[FIN].PWBI_17_VENTAS_Road_Freight
[FIN].PWBI_18_VENTAS_Intern_Road_Freight
[FIN].PWBI_19_VENTAS_Freight_Adjustment
[FIN].PWBI_19_VENTAS_Storage_Handling
[FIN].PWBI_19_VENTAS_Storage_Warehouse
[FIN].PWBI_19_VENTAS_Total_Freight